# jsp
spring :
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      location: d:/temp/
  profiles:
    active:
    - dblocal
    - redislocal
    - tomcatlocal
    - elasticlocal
    - kafkaLocal
    - mysqllocal
    profiles: elasticlocal
  elasticsearch:
    clusterName: luna-lms
    host: 127.0.0.1
    port: 9300
    resthost: 127.0.0.1
    restport: 9200
      
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  main:
    web-application-type: servlet

  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:mariadb://13.125.216.41:3306/howstudy?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin1234

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.demo.vo

server:
  tomcat: 
    accesslog:
      enabled: true
      directory: logs
      suffix: .log
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      pattern: '[%{yyyy-MM-dd HH:mm:ss}t] %s "%r" %{User-Agent}i %{Referer}i %a %b'
    basedir: .

  port: 0   # 외부 Tomcat 사용 시 무시됨, 내장 서버 비활성화용
